/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cloudbeauty.telas;

import br.com.cloudbeauty.constantes.Constantes;
import javax.swing.JOptionPane;

/**
 *
 * @author Debug
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        preencheLabels();
    }

    public void preencheLabels(){
        labelTitulo.setText(Constantes.TITULO);
        labelUsuario.setText(Constantes.USUARIO);
        labelData.setText("Este é um protótipo do sistema.");
    }
    
    public void sair(){
        System.exit(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelBaixo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        barraFerramentas = new javax.swing.JToolBar();
        btClientes = new javax.swing.JButton();
        btColaboradores = new javax.swing.JButton();
        btSobre = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuColaboradores = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenuItem();
        separaMenu = new javax.swing.JPopupMenu.Separator();
        menuLogoff = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelClientes = new javax.swing.JMenuItem();
        menuRelColaboradores = new javax.swing.JMenuItem();
        menuRelAgendamento = new javax.swing.JMenuItem();
        menuRelUsuarios = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        menuTeclasAtalho = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuSobreSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelTitulo.setText("jLabel1");

        labelData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelData.setText("jLabel1");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("jLabel1");

        javax.swing.GroupLayout panelBaixoLayout = new javax.swing.GroupLayout(panelBaixo);
        panelBaixo.setLayout(panelBaixoLayout);
        panelBaixoLayout.setHorizontalGroup(
            panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaixoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(242, 242, 242)
                .addComponent(labelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBaixoLayout.setVerticalGroup(
            panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBaixoLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(panelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(labelData)
                    .addComponent(labelUsuario)))
        );

        barraFerramentas.setFloatable(false);
        barraFerramentas.setRollover(true);

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudbeauty/images/mobile_group_icon_n.png"))); // NOI18N
        btClientes.setToolTipText("Clientes");
        btClientes.setFocusable(false);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClientes.setMaximumSize(new java.awt.Dimension(55, 55));
        btClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(btClientes);

        btColaboradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudbeauty/images/icon-people.png"))); // NOI18N
        btColaboradores.setToolTipText("Colaboradores");
        btColaboradores.setFocusable(false);
        btColaboradores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btColaboradores.setMaximumSize(new java.awt.Dimension(55, 55));
        btColaboradores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(btColaboradores);

        btSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudbeauty/images/iconCalendar.png"))); // NOI18N
        btSobre.setToolTipText("Agendamento");
        btSobre.setFocusable(false);
        btSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSobre.setMaximumSize(new java.awt.Dimension(55, 55));
        btSobre.setPreferredSize(new java.awt.Dimension(55, 55));
        btSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(btSobre);

        menuSistema.setText("Início");
        menuSistema.setMinimumSize(new java.awt.Dimension(37, 19));

        menuLogin.setText("Login");
        menuLogin.setPreferredSize(new java.awt.Dimension(135, 22));
        menuSistema.add(menuLogin);

        menuClientes.setText("Clientes");
        menuClientes.setPreferredSize(new java.awt.Dimension(135, 22));
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuSistema.add(menuClientes);

        menuColaboradores.setText("Colaboradores");
        menuColaboradores.setPreferredSize(new java.awt.Dimension(135, 22));
        menuColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColaboradoresActionPerformed(evt);
            }
        });
        menuSistema.add(menuColaboradores);

        menuAgendamento.setText("Agendamento");
        menuAgendamento.setPreferredSize(new java.awt.Dimension(135, 22));
        menuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendamentoActionPerformed(evt);
            }
        });
        menuSistema.add(menuAgendamento);
        menuSistema.add(separaMenu);

        menuLogoff.setText("Logoff");
        menuLogoff.setPreferredSize(new java.awt.Dimension(135, 22));
        menuSistema.add(menuLogoff);

        menuSair.setText("Sair");
        menuSair.setPreferredSize(new java.awt.Dimension(135, 22));
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuSair);

        menu.add(menuSistema);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.setMinimumSize(new java.awt.Dimension(37, 19));

        menuRelClientes.setText("Clientes");
        menuRelClientes.setPreferredSize(new java.awt.Dimension(135, 22));
        menuRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelClientesActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelClientes);

        menuRelColaboradores.setText("Colaboradores");
        menuRelColaboradores.setPreferredSize(new java.awt.Dimension(135, 22));
        menuRelColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelColaboradoresActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelColaboradores);

        menuRelAgendamento.setText("Agendamento");
        menuRelAgendamento.setPreferredSize(new java.awt.Dimension(135, 22));
        menuRelAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelAgendamentoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelAgendamento);

        menuRelUsuarios.setText("Usuários");
        menuRelUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelUsuariosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelUsuarios);

        menu.add(menuRelatorios);

        menuFerramentas.setText("Ferramentas");
        menuFerramentas.setMinimumSize(new java.awt.Dimension(37, 19));

        menuTeclasAtalho.setText("Teclas de Atalho");
        menuTeclasAtalho.setPreferredSize(new java.awt.Dimension(135, 22));
        menuFerramentas.add(menuTeclasAtalho);

        menu.add(menuFerramentas);

        menuSobre.setText("Sobre");
        menuSobre.setMinimumSize(new java.awt.Dimension(37, 19));

        menuSobreSistema.setText("Sobre o sistema");
        menuSobreSistema.setPreferredSize(new java.awt.Dimension(135, 22));
        menuSobre.add(menuSobreSistema);

        menu.add(menuSobre);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separador))
                .addContainerGap())
            .addComponent(barraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

        if(JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saída do Sistema", JOptionPane.YES_NO_OPTION) == 0){
            sair();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed

        Clientes cliente = new Clientes(this, false);
        
        cliente.setTitle("Clientes");
        cliente.setLocationRelativeTo(cliente);
        cliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColaboradoresActionPerformed

        Colaborador colaborador = new Colaborador(this, true);
        colaborador.setLocationRelativeTo(colaborador);
        colaborador.setTitle("Colaboradores");
        colaborador.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuColaboradoresActionPerformed

    private void menuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendamentoActionPerformed

        Agendamento agendamento = new Agendamento(this, true);
        agendamento.setTitle("Agendamento");
        agendamento.setLocationRelativeTo(agendamento);
        agendamento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAgendamentoActionPerformed

    private void menuRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelClientesActionPerformed

        RelatorioCliente relatorioCli = new RelatorioCliente(this, true);
        
        relatorioCli.setTitle("Relatório de Clientes");
        relatorioCli.setLocationRelativeTo(relatorioCli);
        relatorioCli.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelClientesActionPerformed

    private void menuRelColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelColaboradoresActionPerformed

        RelatorioColaborador relColaborador = new RelatorioColaborador(this, true);
        relColaborador.setTitle("Relatório de Colaboradores");
        relColaborador.setLocationRelativeTo(relColaborador);
        relColaborador.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelColaboradoresActionPerformed

    private void menuRelAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelAgendamentoActionPerformed

        RelatorioAgendamento relAgendamento = new RelatorioAgendamento(this, true);
        relAgendamento.setTitle("Relatório de Agendamentos");
        relAgendamento.setLocationRelativeTo(relAgendamento);
        relAgendamento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelAgendamentoActionPerformed

    private void menuRelUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelUsuariosActionPerformed
        RelatorioUsuarios relUsuarios = new RelatorioUsuarios(this, true);
        relUsuarios.setTitle("Relatório de Usuários");
        relUsuarios.setLocationRelativeTo(relUsuarios);
        relUsuarios.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerramentas;
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btColaboradores;
    private javax.swing.JButton btSobre;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAgendamento;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuColaboradores;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogoff;
    private javax.swing.JMenuItem menuRelAgendamento;
    private javax.swing.JMenuItem menuRelClientes;
    private javax.swing.JMenuItem menuRelColaboradores;
    private javax.swing.JMenuItem menuRelUsuarios;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem menuSobreSistema;
    private javax.swing.JMenuItem menuTeclasAtalho;
    private javax.swing.JPanel panelBaixo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPopupMenu.Separator separaMenu;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
